CREATE TABLE users (
	id INT IDENTITY(1,1) PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(20) NOT NULL 
		CHECK (role IN ('ADMIN', 'STAFF', 'CUSTOMER')) DEFAULT 'CUSTOMER',
	address TEXT,
	telephone VARCHAR(20),
	status VARCHAR(20) 
		CHECK (status IN ('ACTIVE', 'INACTIVE')) DEFAULT 'ACTIVE',
	reset_token VARCHAR(255) NULL,
	reset_token_expiry DATETIME NULL,
	created_at DATETIME DEFAULT GETDATE(),
	updated_at DATETIME DEFAULT GETDATE()
);