export const FOOD_CATEGORIES = ["All", "Rice", "Burger", "Pizza", "Drinks"];

export const DEMO_FOODS = [
  {
    id: 1,
    name: "Chicken Kottu",
    category: "Rice",
    price: 8.5,
    rating: 4.7,
    stock: 24,
    prepTime: "15 min",
    description: "A popular Sri Lankan style street food with chicken and vegetables.",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 2,
    name: "Cheese Burger",
    category: "Burger",
    price: 6.75,
    rating: 4.5,
    stock: 18,
    prepTime: "10 min",
    description: "Juicy burger with melted cheese, fresh salad, and house sauce.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 3,
    name: "Pepperoni Pizza",
    category: "Pizza",
    price: 11.99,
    rating: 4.8,
    stock: 12,
    prepTime: "20 min",
    description: "Classic pizza with pepperoni, mozzarella, and tomato sauce.",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 4,
    name: "Iced Coffee",
    category: "Drinks",
    price: 3.25,
    rating: 4.4,
    stock: 30,
    prepTime: "5 min",
    description: "Refreshing cold coffee for a quick energy boost.",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 5,
    name: "Veggie Rice Bowl",
    category: "Rice",
    price: 7.2,
    rating: 4.3,
    stock: 20,
    prepTime: "12 min",
    description: "Healthy rice bowl with mixed vegetables and a light sauce.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 6,
    name: "Chicken Burger",
    category: "Burger",
    price: 7.4,
    rating: 4.6,
    stock: 16,
    prepTime: "11 min",
    description: "Crispy chicken burger with lettuce and creamy mayo.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
  },
];

export const DEMO_USERS = [
  { id: 1, name: "Admin User", email: "admin@smartfood.com", role: "admin" },
  { id: 2, name: "Jane Student", email: "jane@student.com", role: "customer" },
  { id: 3, name: "Kasun Silva", email: "kasun@email.com", role: "customer" },
];

export const DEMO_ORDERS = [
  {
    id: "ORD-1001",
    customerName: "Jane Student",
    items: [
      { name: "Chicken Kottu", quantity: 1 },
      { name: "Iced Coffee", quantity: 2 },
    ],
    total: 15,
    status: "Delivered",
    progress: 100,
    date: "2026-03-18",
  },
  {
    id: "ORD-1002",
    customerName: "Kasun Silva",
    items: [{ name: "Pepperoni Pizza", quantity: 1 }],
    total: 11.99,
    status: "Preparing",
    progress: 60,
    date: "2026-03-19",
  },
  {
    id: "ORD-1003",
    customerName: "Jane Student",
    items: [{ name: "Cheese Burger", quantity: 2 }],
    total: 13.5,
    status: "Pending",
    progress: 20,
    date: "2026-03-20",
  },
];
